
script_writing:
  description: >
    Yanıt Yapısı:
    
    Dönüş yapacağın bilgilerin dili {language} olmalı. 
    Örneğin Türkçe ise, dönüş yapacağın bilgiler Türkçe olmalı. 
      Indonesian ise Endonezyaca olmalı.
    Bu kural tüm fieldlar için geçerli. {language} dışında bir dil kullanamazsın.
    
    sadece eğer ending_verse_no değeri 0 dan farklı ise o zaman {verse_no} ile {ending_verse_no} arasındaki ayetleri paylaş.
    
    sadece eğer ending_verse_no 0'a eşit ise o zaman kullanıcının belirttiği sure ({surah_name}) ve belirttiği ayet numarasına ({verse_no}) bak. 
    Bu ayet ile aynı bağlamı taşıması halinde ondan sonra gelen ayetleri paylaş.
    
    Örneğin ending_verse_no 0 ve verse_no 2 ise 2. ayetten sonra gelen aynı bağlam içerisinde yer alan tüm ayetleri paylaş.
    
    Örneğin ending_verse_no 5 ve verse_no 2 ise 2. ayetten 5. ayete kadar olan tüm ayetleri paylaş.
    
    Ayetlerin mealini bulacağın kaynaklar {language} dilinde olmalı.
    {language} dili haricindeki kaynakları kullanma ve bu mealleri paylaşma.
    
    Ayetlerin tercümelerini paylaşırken, sadece bulduğun kaynaklarda yazan metinleri paylaşacaksın asla kendince bir yorum veya açıklama eklemeyeceksin.
    Ondan önceki ayetler bağlam olarak ilişkili olsa bile eklemeyeceksin.
    
    Alttaki temel kurallara sıkı sıkıya uyacaksın!
    - besmele field'ina müslümanlarca besmele olarak bilinen fatiha suresinin birinci ayetini, sana verilmiş olan {language} dilindeki karşılı neyse o olacak şekilde yazacaksın.
      Cümle tamamlandıktan sonra mutlaka nokta işaretini koyacaksın.
      Örneğin dil Türkçe ise "Rahman ve Rahim olan Allah'ın adıyla.", İngilizce ise "In the name of Allah, the Most Gracious, the Most Merciful." olacak.
    
    - sadakallhulazim field'ına, müslümanların bir kuran ayeti okuduktan sonra söyledikleri arapça okunuşu Sadakallahulazim olan ve türkçesi "Yüce Allah doğru söyledi" şeklinde tercüme edilen cümlenin {language} dilindeki karşılığı neyse onu yazacaksın.
      Cümle tamamlandıktan sonra mutlaka nokta işaretini koyacaksın.
      Örneğin {language} Türkçe ise "Yüce Allah doğru söyledi.", ingilizce ise "The Almighty Allah has spoken the truth.", almanca ise "Der Allmächtige Allah hat die Wahrheit gesprochen" olacak.
    
    - Surenin adı {language} dilde yaz.
      Örneğin dil Türkçe ise "Bakara", İngilizce ise "The Cow" olacak.
    
    - surah_number fieldinda surenin kaçıncı sure olduğunu belirt. 
      Örneğin Bakara Suresi için 2, Fatiha Suresi için 1 olacak.

    - surah_name_and_verse_numbers Sure ismi ve bahsi geçen ayet numaralarının ilk ve sonuncusu olacak şekilde {language} dilinde yaz.
      Örneğin dil Türkçe ise "Bakara Suresi - 1 ile 5. Ayetler", İngilizce ise "The Cow - Verses 1 to 5" olacak.
    
    - Tefsiri, 40 kelime olacak ve en fazla 2 cümleden oluşacak şekilde {language} dilinde yaz. 
      Tefsiri yazarken az bilinen ancak önemli olduğunu düşündüğün bir bilgiyi de ekle.
    
    - Bu tefsiri özetleyen {language} dilinde 6 tane tag oluştur. Bu taglerin her biri en fazla 12 karakter olmalı ve tefsirde geçen önemli kelimeleri temsil etmeli.
      Birinci tag her zaman {language} dilinin kendi dilindeki adını içermeli.  
      Tüm taglar mutlaka küçük harfle yazılmalı ve taglar arasında boşluk olmalı. Ancak tek bir taga ait kelimelerde boşluk olmamalı.
      Birden fazla kelimeden bir tag oluşuyorsa en fazla iki kelime kullanılmalı ve aralarında boşluk olmamalı.
      Örneğin tefsir Türkçe dilinde ve "Allah'ın rahmeti her şeyi kuşatmıştır" cümlesi şeklinde ise tagler "#türkçe #rahmet #kuşatma" gibi olmalı.
      Örneğin verilen language fieldindaki dil ({language}) Turkish ise taglar "#türkçe #allah #kuran #islam #müslüman #namaz" gibi olmalı.
      Örneğin verilen language fieldindaki dil ({language}) English ise tagler "#english #allah #quran #islam #muslim #prayer" gibi olmalı.
      Örneğin verilen language fieldindaki dil ({language}) Russian ise taglar "#Русский #Аллах #Коран #Ислам #Мусульманин #Молитва" gibi olmalı.
      Örneğin verilen language fieldindaki dil ({language}) Indonesian ise taglar "#bahasaindonesia #Allah #Al-Qur'an #islam #muslim #sholat" gibi olmalı.
    
    - Kur'an’ın inmeye başladığı yıla göre hangi dönemde ve nerede indiğini {language} dilinde belirt. Açıklama eklemeden sadece tarih ve yer belirt.
      Cümle tamamlandıktan sonra mutlaka nokta işaretini koyacaksın.
      Örneğin {language} dili Turkish ise "Mekke'de hicri 1. yıl.", English ise "Mecca in the first year of Hijra." şeklinde olmalı.
    
    - Listedeki en son ayetin numarasını ilgili field'a değer olarak ver.
    
    - Asla sadece ilk ayeti tek başına yanıt olarak verme. Mutlaka ayetlerin bağlamı korunarak ondan sonra gelen ayetlerle birlikte döndür.
    
    - Elif, Lam, Mim gibi sadece harf içeren ayetleri asla tek başına yanıt olarak dönme, kendilerinden sonra gelen ayetlerle birlikte gruplandır.
    
    - Kaynaklarda edindiğinin haricinde kendin asla bir yorum, açıklama, bilgi ekleyemezsin.
    
    - Paylaşırken ilk ayetten son ayete göre sıralama yapacaksın
    
    - Asla Amin kelimesini son ayet olarak vermeyeceksin. 
    
    - İlgili ayet kaynakta belirtilen ilgili ayet numarasında değilse kendince uydurup bunu paylaşamazsın!
    
    fill surah_name_and_verse_numbers as the following:
    Sura Name - Verse first to end
    For example:
    Cow - Verses 1 to 5
    If the language is turkish, then the sura name should be in turkish and the verse numbers should be in turkish like following.
    Bakara Suresi - 1 ile 5. Ayetler
    These rules should be followed strictly and must be exactly apply for the other languages.

    Tefsir (1 Cümle):
    [Ayet(ler)in kısa bir anlam özeti.]

    Kur'an'ın İnme Yılına Göre Zamanı ve Yeri:
    [Ayet(ler)in indirildiği dönem ve yer.]
    
    Array içindeki son ayetin numarası
  expected_output: >
    The output must follow the pydantic schema strictly. There will be penalty if not followed.
  agent: script_writer_agent


script_reduction:
  description: >
    {language} dilinde paylaşılan Kuran ayetlerinin gerçekten resmi kaynaklardan geldiğinin doğruluğunu kontrol edeceksin.
    
    Aynı ayetin birden fazla kez paylaşılmasını engelleyeceksin.
    
    Numarası ile birlikte verilen ayetin, gerçekten kuran'da o sure'nin içindeki o ayet numarasında doğru olduğundan emin olacaksın.
    
    Ayetlerin doğru sıralanmasını sağla.
    
    Eğer yanlış bir ayet varsa, onu listeden çıkart.
    
    Çevirinin doğruluğundan emin ol.
    
    Ayetlerin doğru sıralanmasını sağla.
    
    Aynı ayetin birden fazla kez paylaşılmasına asla izin verme fakat kuran'da bazı ayetler birden fazla kez tekrarlanabilir. 
    
    Bu durumlarda ayet numarasını doğrula. Gerçekten o ayet o ayet numarasına sahipse paylaşmaya devam et. 
    
    Asla ayetlerin liste halinde tutulduğu verses listesinin içine amin şeklinde bir ayet ekleme, varsa çıkart.
    
    Never make change on the value or remove the value in the field named "amen" by given previous agent.
    
    Kurallara sıkı sıkıya bağlı kal
  expected_output: >
    The output must follow the pydantic schema strictly. There will be penalty if not followed.
  agent: script_reduction_agent