writing_task:
  description: >
    {question} sorusuna ortalama 5 dakikalık videoda anlatılacak şekilde yanıt içeren metin oluşturacaksın.
    Sorunun yanıtını {analogy} ile analojilendirerek cevap vereceksin. 
    Çocukların da anlayabileceği basit bir dil kullanarak, karmaşık konuları basitleştirecek şekilde cevap vereceksin.
    Örneğin: Enerji nedir diye sorulduğunda enerjiyi ve enerji ile alakalı her terimi elma ile açıklayarak cevap vereceksin.
    
    Verdiğin cevabı cümleler halinde sentences listesine ekleyeceksin. sentences listesinin 3 adet fieldı var, number, image_prompt ve text.
        Verdiğin yanıt toplamda 10 sentence itemından oluşacak ve içinde mutlaka okuyucunun çokça ilgisini çekeceği bilgi veya anektodlar olacak.     
        number fieldı cümlenin sırasını belirtirken, text fieldı cümleyi belirtecek.
        Birinci sentence her zaman aşağıdaki formatta olacak:
          Örneğin: question fieldı "Türkiye'nin en büyük gölü" diye verildiyse,
          birinci sentence "Türkiye'nin en büyük gölü bir elma gibi olsaydı" şeklinde olmalı. buradaki elma, analogy fildında gelen değer neyse o ({analogy}).
        Tabi bu şablon verilen dile göre değişmeli.
          Örneğin: verilen dil ingilizce ise "If largest lake in Turkey were an apple?" olmalı.
          Örneğin: verilen dil ingilizce ve sorulan soru "what is evolution" ise birinci sentence "What If energy were an apple?" olmalı.
  
    Cümleler arasında mantıklı bir bağlantı olmalı ve akıcı bir anlatım olmalı.
    Birinci cümle ile konsept açıklamasına başlarken, son cümle ile de konseptin açıklamasını bitirdiğin bir akış çizmelisin.
    
    Her text fieldı ikişer cümleden oluşacak. 
    text fieldının birinci cümlesi soru ile ilgili normal yanıtı verirken, ikinci cümle ise bunu bir analoji ile herkesin anlayacağı şekilde açıklayacak.
    Örnek:
        Martin Luther King Jr kimdir? diye sorulduğunu varsayalım ve {analogy} olarak "bir elma" seçildiğini varsayalım.
        Cevap şu şekilde olabilir:
        Martin Luther King Jr., ırksal eşitlik için mücadele eden bir sivil haklar lideriydi. Tıpkı farklı renklerde olsalar da aynı tatlılığa sahip elmalar gibi, insanların da ten rengi ne olursa olsun eşit haklara sahip olması gerektiğini savundu.
        Şiddet yerine barışçıl protestoları savundu ve insanlara sevgiyle yaklaşmanın gücüne inandı. Bir elmayı nazikçe sarsarak dalından düşmesini beklersen nasıl zarar görmezse, King de değişimin sert darbelerle değil, sabır ve anlayışla gerçekleşmesi gerektiğini söyledi.
        En ünlü konuşması "I Have a Dream" ile milyonlara ilham verdi. Bir elma tohumu nasıl zamanla büyüyüp koca bir ağaca dönüşüyorsa, onun hayali de yıllar içinde büyüyerek dünyada özgürlük ve eşitlik için güçlü bir etki yarattı.
        Haksızlık karşısında sessiz kalmayı reddederek cesurca adalet için savaştı. Çürümüş bir elmayı görmezden gelirsek, tüm sepetin bozulmasına neden olabileceği gibi, o da ırkçılığı görmezden gelmenin toplumu mahvedeceğini düşündü.
        Onun mücadelesi ölümünden sonra bile etkisini sürdürdü ve birçok insan hakları yasasının çıkmasına öncülük etti. Bir elma yere düştüğünde kaybolmaz, yeni bir ağaç yetiştirerek geleceğe miras bırakır; King de fikirleriyle dünyaya kalıcı bir değişim armağan etti.
      
    Bu şekilde bir cümle asla kurmayacaksın: Teachers often use apples to help students visualize and understand the abstract concept of energy.
    Paylaştığın bilgiler mutlaka hem konu ile ilgili çok çekici hem de konu hakkında bilgilendirici ve eğitici olmalı. 
    Oluşturduğun cümleler ile yanıtını hazırladığında, sorunun tam olarak yanıtının verilmiş ve soruyu soranın konu hakkında yeterince bilgilenmiş olduğundan emin olman gerekli.
      
    Yanıt metnin {language} dilinde olmalı.
      Yanıtta giriş, gelişme ve sonuç şeklinde bir bütünlük olmalı. 
      Örneğin verilen dil ({language}) Türkçe ise, dönüş yapacağın bilgiler de Türkçe olmalı.
      Örneğin verilen dil ({language}) İngilizce ise, dönüş yapacağın bilgiler de İngilizce olmalı.
    
    image_prompt fieldı, cümleye ait oluşturulacak görsel ile ilgili açıklayıcı bir prompt içerecek.
    Oluşturulacak görsel akademik tarih kitaplarında kullanılacak bir görsel olacak.  
    No text. 
    Lush oil painting style. 
    Dimensions should be close to {dimension_type} aspect ratio."
    Olması gereken örnek prompt: 
      "An Lush oil painting style portrait of Genghis Khan, depicted in exquisite detail, wearing traditional Mongolian attire.
      No writing or text should be included in the image. Dimensions should be close to {dimension_type} aspect ratio.
      Dimensions should be suitable for a full-page illustration in an academic history book: 
      His face exudes strength, wisdom, and leadership, with piercing eyes and a commanding presence. 
      The intricate embroidery and textures of his clothing reflect the richness of Mongolian culture. 
      The background features a subtle, historically accurate Mongolian landscape, evoking the vastness of the empire he built. 
      The lighting is dramatic, emphasizing the depth and realism of his facial features, making this a visually compelling and historically informative illustration suitable for an academic history book."
    
      Ayrıca image_prompt için üreteceğin promptlar Dall-E modeli kullanılarak görsel üretecek bu yüzden üreteceğin prompt'un dall-e güvenlik sistemi açısından bir engel oluşturmaması gerekli.
      Üreteceğin promptların hiçbir şekilde şiddet, cinsellik, ırkçılık, nefret söylemi ve benzeri şeyler içermemeli. 
      Sadece bilgilendirici ve eğitici olmalı.
      Yukarıda belirttiğim image_prompt ile ilgili açıklayıcı kurallar çok önemli, asla şiddet, cinsellik, ırkçılık, nefret söylemi ve benzeri bir prompt oluşturmayacaksın.
      Oluşturacağın promptlar sadece ama sadece eğiticilik ve bilgilendiricilik amacı taşıyacak, akademik tarih kitaplarında kullanılabilecek görsellerin oluşturulmasına yardımcı olacak.
      Örneğin Adolf Hitler gibi bir figür ile ilgili bir görsel üretmek istediğimizde bile "20. yüzyıl Almanya'sının şehir hayatını gösteren bir imaj" şeklinde bir prompt oluşturacaksın ancak hiçbir şekilde uygunsuz bir dil kullanmayacaksın.      
    
      image_prompt fieldına ait promptu oluştururken, cümledeki en önemli kelimeleri ve ana konsepti dikkate alarak oluştur. 
      Aynı zamanda sorulan soru ile ilgili verilen cevabın genel temasıyla da paralellik sağla.
      image_prompt için oluşturduğun promptlar dall-e'de yaratılacak görseller için kullanılacak. Bu görsellerin ultrarealistic olması gerekli. 
      Görsellerin gerçekçiliği, kullanıcıların konuyu daha iyi anlamasına yardımcı olacak o yüzden promptlarını açıklayıcı bir şekilde oluştur.
    
    Bu cümleler çok daha uzun olabilir, önemli olan 5 dakikalık süre içerisinde sorulan soruya cevap verebilecek şekilde olması.
    sentences listesindeki cümlelerin toplam uzunluğu ortalama 5 dakikalık bir videoda anlatılabilecek kadar olmalı.
    
    tags fieldı için 5 tane tag belirleyeceksin. Bu tagler verilen soru ile ilgili olmalı.
    taglar {language} dilinde {analogy} ile ilişkili olmalı.
      Örneğin: verilen question "Türkiye'nin en büyük gölü?" ise, tagler #Van Gölü, #elma, #Türkiye, #Göl, #Doğa, #Tatil olabilir.
      Örneğin: verilen question "largest lake in Turkey?" ise, tagler #Van Lake, #apple, #Turkey, #Lake, #Nature, #Holiday olabilir.    

  expected_output: >
    The output must follow the pydantic schema strictly. There will be penalty if not followed.
  agent: writer_agent
