convert_text_to_speech_task:
  description: >
    Convert given text ({input_text}) to speech using the text-to-speech agent.
    You will use the language parameter without converting it to the language code.
    For example: if the language is Turkish then the language parameter should be "Turkish" not "tr".
    For example: if the language is English then the language parameter should be "English" not "en".
    Do conversion in {language} language. 
    Use {voice_id} as the voice id.
    Use {save_path} as output path.
    Use {combined} parameter to whether combine the mp3 or not.
  expected_output: >
    The output file should be saved at {save_path}.
    if {combined} parameter is true then the output files should be combined also in a file called combined.mp3.
  agent: text_to_speech_agent

